--DECLARE
--    t_count NUMBER := 0;
--BEGIN
    --select count(*) into t_count from user_tables where table_name='MBTA_CHARLIE';
    --if t_count > 0
    --   THEN execute immediate 'DROP TABLE MBTA_CHARLIE';
    --END IF;
--END;

begin 
execute immediate 'DROP TABLE MBTA_CHARLIE'; 
exception when others then null; 
end;
/
begin 
execute immediate 'DROP TABLE MBTA_PASSENGER'; 
exception when others then null; 
end;
/
begin 
execute immediate 'DROP TABLE MBTA_PASSENGERFREQUENCY'; 
exception when others then null; 
end;
/
begin 
execute immediate 'DROP TABLE MBTA_LOGIN'; 
exception when others then null; 
end;
/
begin 
execute immediate 'DROP TABLE MBTA_SCHEDULE'; 
exception when others then null; 
end;
/
begin 
execute immediate 'DROP TABLE MBTA_STATION'; 
exception when others then null; 
end;
/
begin 
execute immediate 'DROP TABLE MBTA_ROUTEINFO'; 
exception when others then null; 
end;
/
begin 
execute immediate 'DROP TABLE MBTA_TRAINCURRENTSTATUS'; 
exception when others then null; 
end;
/
begin 
execute immediate 'DROP TABLE MBTA_TRAININFO'; 
exception when others then null; 
end;
/
begin 
execute immediate 'DROP TABLE MBTA_TRANSACTION'; 
exception when others then null; 
end;
/
begin 
execute immediate 'DROP TABLE MBTA_TYPES'; 
exception when others then null; 
end;
/
begin 
execute immediate 'DROP TABLE MBTA_EMPLOGIN'; 
exception when others then null; 
end;
/
begin 
execute immediate 'DROP TABLE MBTA_EMPLOYEE'; 
exception when others then null; 
end;
/
begin 
execute immediate 'DROP TABLE MBTA_DEPT'; 
exception when others then null; 
end;
/
begin 
execute immediate 'DROP TABLE MBTA_DEPTTYPE'; 
exception when others then null; 
end;
/


--DROP table MBTA_CHARLIE;
--DROP TABLE MBTA_PASSENGER;
--DROP TABLE MBTA_PASSENGERFREQUENCY;
--DROP TABLE MBTA_LOGIN;
--DROP TABLE MBTA_SCHEDULE;
--DROP TABLE MBTA_STATION;
--DROP TABLE MBTA_ROUTEINFO;
--DROP TABLE MBTA_TRAINCURRENTSTATUS;
--DROP TABLE MBTA_TRAININFO;
--DROP TABLE MBTA_TRANSACTION;
--DROP TABLE MBTA_TYPES;
--DROP TABLE MBTA_EMPLOGIN;
--DROP TABLE MBTA_EMPLOYEE;
--DROP TABLE MBTA_DEPT;
--DROP TABLE MBTA_DEPTTYPE;

--------------------------------------------------------
--  DDL for Table MBTA_DEPTTYPE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_DEPTTYPE" 
   (	"DEPTTYPEID" NUMBER(*,0), 
	"DEPTNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027598
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027598" ON "ADMIN"."MBTA_DEPTTYPE" ("DEPTTYPEID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MBTA_DEPTTYPE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_DEPTTYPE" MODIFY ("DEPTTYPEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_DEPTTYPE" MODIFY ("DEPTNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_DEPTTYPE" ADD PRIMARY KEY ("DEPTTYPEID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;


--------------------------------------------------------
--  DDL for Table MBTA_DEPT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_DEPT" 
   (	"DEPTID" NUMBER(*,0), 
	"DEPTTYPEID" NUMBER(*,0), 
	"ROLE" NVARCHAR2(255) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027631
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027631" ON "ADMIN"."MBTA_DEPT" ("DEPTID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MBTA_DEPT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_DEPT" MODIFY ("DEPTID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_DEPT" MODIFY ("DEPTTYPEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_DEPT" ADD PRIMARY KEY ("DEPTID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MBTA_DEPT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_DEPT" ADD FOREIGN KEY ("DEPTTYPEID")
	  REFERENCES "ADMIN"."MBTA_DEPTTYPE" ("DEPTTYPEID") ENABLE;


--------------------------------------------------------
--  DDL for Table MBTA_EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_EMPLOYEE" 
   (	"EMPLOYEEID" NUMBER(*,0), 
	"DEPTID" NUMBER(*,0), 
	"TRAINID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"AGE" NUMBER(*,0), 
	"ADDRESS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ZIPCODE" NUMBER(*,0), 
	"DOJ" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027595
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027595" ON "ADMIN"."MBTA_EMPLOYEE" ("EMPLOYEEID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

--------------------------------------------------------
--  Constraints for Table MBTA_EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" MODIFY ("EMPLOYEEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" MODIFY ("DEPTID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" MODIFY ("ZIPCODE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" MODIFY ("DOJ" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" ADD PRIMARY KEY ("EMPLOYEEID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MBTA_EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" ADD FOREIGN KEY ("DEPTID")
	  REFERENCES "ADMIN"."MBTA_DEPT" ("DEPTID") ENABLE;


--------------------------------------------------------
--  DDL for Table MBTA_EMPLOGIN
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_EMPLOGIN" 
   (	"LOGINID" NUMBER(*,0), 
	"EMPLOYEEID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSWORD" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027577
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027577" ON "ADMIN"."MBTA_EMPLOGIN" ("LOGINID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MBTA_EMPLOGIN
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_EMPLOGIN" MODIFY ("LOGINID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOGIN" MODIFY ("EMPLOYEEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOGIN" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOGIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOGIN" ADD PRIMARY KEY ("LOGINID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MBTA_EMPLOGIN
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_EMPLOGIN" ADD CONSTRAINT "FK_EMP_LOGIN" FOREIGN KEY ("EMPLOYEEID")
	  REFERENCES "ADMIN"."MBTA_EMPLOYEE" ("EMPLOYEEID") ENABLE;



-------------------------------------Saksheee Part-----------------------------------------

--------------------------------------------------------
--  DDL for Table MBTA_LOGIN
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_LOGIN" 
   (	"LOGINID" NUMBER(*,0), 
	"PASSENGERID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSWORD" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027572
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027572" ON "ADMIN"."MBTA_LOGIN" ("LOGINID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027635
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027635" ON "ADMIN"."MBTA_LOGIN" ("PASSENGERID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MBTA_LOGIN
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_LOGIN" MODIFY ("LOGINID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_LOGIN" MODIFY ("PASSENGERID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_LOGIN" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_LOGIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_LOGIN" ADD PRIMARY KEY ("LOGINID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "ADMIN"."MBTA_LOGIN" ADD UNIQUE ("PASSENGERID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;


--------------------------------------------------------
--  DDL for Table MBTA_PASSENGER
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_PASSENGER" 
   (	"PASSENGERID" NUMBER(*,0), 
	"PASSENGERFNAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSENGERLNAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"DOB" DATE, 
	"ADDRESS" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CITY" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"STATE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"ZIPCODE" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027628
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027628" ON "ADMIN"."MBTA_PASSENGER" ("PASSENGERID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;


--------------------------------------------------------
--  Constraints for Table MBTA_PASSENGER
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_PASSENGER" MODIFY ("PASSENGERID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGER" MODIFY ("PASSENGERFNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGER" MODIFY ("PASSENGERLNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGER" MODIFY ("DOB" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGER" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGER" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGER" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGER" MODIFY ("ZIPCODE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGER" ADD PRIMARY KEY ("PASSENGERID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MBTA_PASSENGER
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_PASSENGER" ADD FOREIGN KEY ("PASSENGERID")
	  REFERENCES "ADMIN"."MBTA_LOGIN" ("PASSENGERID") ENABLE;



--------------------------------------------------------
--  DDL for Table MBTA_CHARLIE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_CHARLIE" 
   (	"CHARLIEID" NUMBER(*,0), 
	"PASSENGERID" NUMBER(*,0), 
	"BALANCE" NUMBER(*,0), 
	"CARDNUMBER" NUMBER(*,0), 
	"CVVNO" NUMBER(*,0), 
	"EXPIRATIONDATE" DATE, 
	"TRANCHEID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027582
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027582" ON "ADMIN"."MBTA_CHARLIE" ("CHARLIEID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MBTA_CHARLIE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_CHARLIE" MODIFY ("CHARLIEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_CHARLIE" MODIFY ("PASSENGERID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_CHARLIE" ADD PRIMARY KEY ("CHARLIEID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MBTA_CHARLIE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_CHARLIE" ADD FOREIGN KEY ("PASSENGERID")
	  REFERENCES "ADMIN"."MBTA_PASSENGER" ("PASSENGERID") ENABLE;


--------------------------------------------------------
--  DDL for Table MBTA_TRANSACTION
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_TRANSACTION" 
   (	"TRANSACTIONID" NUMBER(*,0), 
	"PASSENGERID" NUMBER(*,0), 
	"AMOUNT" NUMBER(*,0), 
	"TRANCHEID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index MBTA_TRANSACTION_INDEX
--------------------------------------------------------

  CREATE INDEX "ADMIN"."MBTA_TRANSACTION_INDEX" ON "ADMIN"."MBTA_TRANSACTION" ("TRANCHEID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027585
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027585" ON "ADMIN"."MBTA_TRANSACTION" ("TRANSACTIONID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MBTA_TRANSACTION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_TRANSACTION" MODIFY ("TRANSACTIONID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_TRANSACTION" MODIFY ("PASSENGERID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_TRANSACTION" ADD PRIMARY KEY ("TRANSACTIONID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;


--------------------------------------------------------
--  DDL for Table MBTA_PASSENGERFREQUENCY
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Table MBTA_STATION
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_STATION" 
   (	"STATIONID" NUMBER(*,0), 
	"ROUTEID" NUMBER(*,0), 
	"STATIONNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"STATIONZIPCODE" NUMBER(*,0), 
	"LATITUDE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"LONGITUDE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"STATIONSEQ" NUMBER(5,0), 
	"PREVSEQ" NUMBER(5,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027619
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027619" ON "ADMIN"."MBTA_STATION" ("STATIONID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MBTA_STATION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_STATION" ADD CHECK (status in ('Y','N')) ENABLE;
  ALTER TABLE "ADMIN"."MBTA_STATION" MODIFY ("STATIONID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_STATION" MODIFY ("ROUTEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_STATION" MODIFY ("STATIONNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_STATION" MODIFY ("STATIONZIPCODE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_STATION" ADD PRIMARY KEY ("STATIONID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;



  CREATE TABLE "ADMIN"."MBTA_PASSENGERFREQUENCY" 
   (	"FREQUENCYID" NUMBER(*,0), 
	"STATIONID" NUMBER(*,0), 
	"AVGSEC" NUMBER(5,2), 
	"STDSEC" NUMBER(5,2), 
	"DAYTYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSENGERID" NUMBER(*,0), 
	"PEAKINDEX" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027563
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027563" ON "ADMIN"."MBTA_PASSENGERFREQUENCY" ("FREQUENCYID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MBTA_PASSENGERFREQUENCY
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_PASSENGERFREQUENCY" MODIFY ("FREQUENCYID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGERFREQUENCY" MODIFY ("STATIONID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGERFREQUENCY" MODIFY ("AVGSEC" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGERFREQUENCY" MODIFY ("STDSEC" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGERFREQUENCY" MODIFY ("DAYTYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGERFREQUENCY" MODIFY ("PASSENGERID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGERFREQUENCY" ADD PRIMARY KEY ("FREQUENCYID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MBTA_PASSENGERFREQUENCY
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_PASSENGERFREQUENCY" ADD FOREIGN KEY ("STATIONID")
	  REFERENCES "ADMIN"."MBTA_STATION" ("STATIONID") ENABLE;


--------------------------------------------------------
--  DDL for Table MBTA_TYPES
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_TYPES" 
   (	"TYPEID" NUMBER(*,0), 
	"TYPENAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027555
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027555" ON "ADMIN"."MBTA_TYPES" ("TYPEID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MBTA_TYPES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_TYPES" MODIFY ("TYPEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_TYPES" MODIFY ("TYPENAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_TYPES" ADD PRIMARY KEY ("TYPEID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;


--------------------------------------------------------
--  DDL for Table MBTA_ROUTEINFO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_ROUTEINFO" 
   (	"ROUTEID" NUMBER(*,0), 
	"TYPEID" NUMBER(*,0), 
	"ROUTE_FROM" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ROUTE_TO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DURATION" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027552
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027552" ON "ADMIN"."MBTA_ROUTEINFO" ("ROUTEID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MBTA_ROUTEINFO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" MODIFY ("ROUTEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" MODIFY ("TYPEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" MODIFY ("ROUTE_FROM" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" MODIFY ("ROUTE_TO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" MODIFY ("DURATION" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" ADD PRIMARY KEY ("ROUTEID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MBTA_ROUTEINFO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" ADD FOREIGN KEY ("TYPEID")
	  REFERENCES "ADMIN"."MBTA_TYPES" ("TYPEID") ENABLE;
      
--------------------------------------------------------
--  Ref Constraints for Table MBTA_STATION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_STATION" ADD FOREIGN KEY ("ROUTEID")
	  REFERENCES "ADMIN"."MBTA_ROUTEINFO" ("ROUTEID") ENABLE;

--------------------------------------------------------
--  DDL for Table MBTA_TRAININFO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_TRAININFO" 
   (	"TRAINID" NUMBER(*,0), 
	"TRAINSERIALNO" NUMBER(*,0), 
	"YEAROFMANUFACTURING" NUMBER(4,0), 
	"LASTSERVICEDATE" DATE, 
	"CAPACITY" NUMBER(*,0), 
	"EMPLOYEEID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027539
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027539" ON "ADMIN"."MBTA_TRAININFO" ("TRAINID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MBTA_TRAININFO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_TRAININFO" MODIFY ("TRAINID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_TRAININFO" MODIFY ("TRAINSERIALNO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_TRAININFO" MODIFY ("YEAROFMANUFACTURING" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_TRAININFO" MODIFY ("CAPACITY" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_TRAININFO" MODIFY ("EMPLOYEEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_TRAININFO" ADD PRIMARY KEY ("TRAINID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MBTA_TRAININFO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_TRAININFO" ADD FOREIGN KEY ("EMPLOYEEID")
	  REFERENCES "ADMIN"."MBTA_EMPLOYEE" ("EMPLOYEEID") ENABLE;


--------------------------------------------------------
--  DDL for Table MBTA_SCHEDULE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_SCHEDULE" 
   (	"SCHEDULEID" NUMBER(*,0), 
	"TRAINID" NUMBER(*,0), 
	"ROUTEID" NUMBER(*,0), 
	"TRAINTIME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027544
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027544" ON "ADMIN"."MBTA_SCHEDULE" ("SCHEDULEID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MBTA_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_SCHEDULE" MODIFY ("SCHEDULEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_SCHEDULE" MODIFY ("TRAINID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_SCHEDULE" MODIFY ("ROUTEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_SCHEDULE" MODIFY ("TRAINTIME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_SCHEDULE" ADD PRIMARY KEY ("SCHEDULEID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MBTA_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_SCHEDULE" ADD FOREIGN KEY ("TRAINID")
	  REFERENCES "ADMIN"."MBTA_TRAININFO" ("TRAINID") ENABLE;
  ALTER TABLE "ADMIN"."MBTA_SCHEDULE" ADD FOREIGN KEY ("ROUTEID")
	  REFERENCES "ADMIN"."MBTA_ROUTEINFO" ("ROUTEID") ENABLE;





--------------------------------------------------------
--  DDL for Table MBTA_TRAINCURRENTSTATUS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_TRAINCURRENTSTATUS" 
   (	"TRAINCURRENTSTATUSID" NUMBER(*,0), 
	"LATITUDE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"LONGITUDE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"TRAINID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027567
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027567" ON "ADMIN"."MBTA_TRAINCURRENTSTATUS" ("TRAINCURRENTSTATUSID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MBTA_TRAINCURRENTSTATUS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_TRAINCURRENTSTATUS" MODIFY ("TRAINCURRENTSTATUSID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_TRAINCURRENTSTATUS" ADD PRIMARY KEY ("TRAINCURRENTSTATUSID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MBTA_TRAINCURRENTSTATUS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_TRAINCURRENTSTATUS" ADD FOREIGN KEY ("TRAINID")
	  REFERENCES "ADMIN"."MBTA_TRAININFO" ("TRAINID") ENABLE;
      
      
--------------------------------------------------------
--  DDL for Trigger DELETE_PASSENGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."DELETE_PASSENGER" 
after delete 
on mbta_passenger 
for each row
declare
begin 
delete from mbta_login where passengerid=:old.passengerid;
delete from mbta_charlie where passengerid=:old.passengerid;
end;

/      
ALTER TRIGGER "ADMIN"."DELETE_PASSENGER" ENABLE;

--------------------------------------------------------
--  DDL for Trigger DELETE_EMPLOYEE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."DELETE_EMPLOYEE" 
after delete
on mbta_employee
for each row 
declare 
begin
delete from mbta_emplogin where employeeid=:old.employeeid;
end;

/
ALTER TRIGGER "ADMIN"."DELETE_EMPLOYEE" ENABLE;
