--------------------------------------------------------
--  DDL for Table MBTA_EMPLOGIN
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_EMPLOGIN" 
   (	"LOGINID" NUMBER(*,0), 
	"EMPLOYEEID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSWORD" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027577
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027577" ON "ADMIN"."MBTA_EMPLOGIN" ("LOGINID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UNK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."UNK" ON "ADMIN"."MBTA_EMPLOGIN" ("EMPLOYEEID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MBTA_EMPLOGIN
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_EMPLOGIN" ADD CONSTRAINT "UNK" UNIQUE ("EMPLOYEEID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "ADMIN"."MBTA_EMPLOGIN" MODIFY ("LOGINID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOGIN" MODIFY ("EMPLOYEEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOGIN" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOGIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOGIN" ADD PRIMARY KEY ("LOGINID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  
  
  
  
  --------------------------------------------------------
--  DDL for Table MBTA_EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_EMPLOYEE" 
   (	"EMPLOYEEID" NUMBER(*,0), 
	"DEPTID" NUMBER(*,0), 
	"TRAINID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"AGE" NUMBER(*,0), 
	"ADDRESS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ZIPCODE" NUMBER(*,0), 
	"DOJ" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027595
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027595" ON "ADMIN"."MBTA_EMPLOYEE" ("EMPLOYEEID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Trigger DELETE_EMPLOYEE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."DELETE_EMPLOYEE" 
before delete
on mbta_employee
for each row 
declare 
begin
delete from mbta_emplogin where employeeid=:old.employeeid;
end;
/
ALTER TRIGGER "ADMIN"."DELETE_EMPLOYEE" ENABLE;
--------------------------------------------------------
--  Constraints for Table MBTA_EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" MODIFY ("EMPLOYEEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" MODIFY ("DEPTID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" MODIFY ("ZIPCODE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" MODIFY ("DOJ" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" ADD PRIMARY KEY ("EMPLOYEEID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MBTA_EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" ADD CONSTRAINT "FK_EMP_EMPLOGIN" FOREIGN KEY ("EMPLOYEEID")
	  REFERENCES "ADMIN"."MBTA_EMPLOGIN" ("EMPLOYEEID") ENABLE;
  ALTER TABLE "ADMIN"."MBTA_EMPLOYEE" ADD FOREIGN KEY ("DEPTID")
	  REFERENCES "ADMIN"."MBTA_DEPT" ("DEPTID") ENABLE;

