--------------------------------------------------------
--  DDL for Table MBTA_ROUTEINFO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_ROUTEINFO" 
   (	"ROUTEID" NUMBER(*,0), 
	"TYPEID" NUMBER(*,0), 
	"ROUTE_FROM" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ROUTE_TO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DURATION" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
