REM INSERTING into ADMIN.MBTA_ROUTEINFO
SET DEFINE OFF;
Insert into ADMIN.MBTA_ROUTEINFO (ROUTEID,TYPEID,ROUTE_FROM,ROUTE_TO,DURATION) values (1,1,'Forest Hills','Oak Grove',37);
Insert into ADMIN.MBTA_ROUTEINFO (ROUTEID,TYPEID,ROUTE_FROM,ROUTE_TO,DURATION) values (2,2,'Alewife','Ashmont',37);
Insert into ADMIN.MBTA_ROUTEINFO (ROUTEID,TYPEID,ROUTE_FROM,ROUTE_TO,DURATION) values (3,2,'Alewife','Braintree',50);
Insert into ADMIN.MBTA_ROUTEINFO (ROUTEID,TYPEID,ROUTE_FROM,ROUTE_TO,DURATION) values (4,3,'Boston College','Lechmere',45);
Insert into ADMIN.MBTA_ROUTEINFO (ROUTEID,TYPEID,ROUTE_FROM,ROUTE_TO,DURATION) values (5,4,'Cleveland Circle','Lechmere',45);
Insert into ADMIN.MBTA_ROUTEINFO (ROUTEID,TYPEID,ROUTE_FROM,ROUTE_TO,DURATION) values (6,5,'Riverside','Lechmere',45);
Insert into ADMIN.MBTA_ROUTEINFO (ROUTEID,TYPEID,ROUTE_FROM,ROUTE_TO,DURATION) values (7,6,'Heath Street','Lechmere',45);
