--------------------------------------------------------
--  Constraints for Table MBTA_ROUTEINFO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" MODIFY ("ROUTEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" MODIFY ("TYPEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" MODIFY ("ROUTE_FROM" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" MODIFY ("ROUTE_TO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" MODIFY ("DURATION" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" ADD PRIMARY KEY ("ROUTEID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
