--------------------------------------------------------
--  File created - Tuesday-December-14-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MBTA_PASSENGERFREQUENCY
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_PASSENGERFREQUENCY" 
   (	"FREQUENCYID" NUMBER(*,0), 
	"STATIONID" NUMBER(*,0), 
	"AVGSEC" NUMBER(5,2), 
	"STDSEC" NUMBER(5,2), 
	"DAYTYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSENGERID" NUMBER(*,0), 
	"PEAKINDEX" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027563
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027563" ON "ADMIN"."MBTA_PASSENGERFREQUENCY" ("FREQUENCYID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MBTA_PASSENGERFREQUENCY
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_PASSENGERFREQUENCY" MODIFY ("FREQUENCYID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGERFREQUENCY" MODIFY ("STATIONID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGERFREQUENCY" MODIFY ("AVGSEC" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGERFREQUENCY" MODIFY ("STDSEC" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGERFREQUENCY" MODIFY ("DAYTYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGERFREQUENCY" MODIFY ("PASSENGERID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_PASSENGERFREQUENCY" ADD PRIMARY KEY ("FREQUENCYID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MBTA_PASSENGERFREQUENCY
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_PASSENGERFREQUENCY" ADD FOREIGN KEY ("STATIONID")
	  REFERENCES "ADMIN"."MBTA_STATION" ("STATIONID") ENABLE;
