--------------------------------------------------------
--  File created - Tuesday-December-14-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MBTA_ROUTEINFO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_ROUTEINFO" 
   (	"ROUTEID" NUMBER(*,0), 
	"TYPEID" NUMBER(*,0), 
	"ROUTE_FROM" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ROUTE_TO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DURATION" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027552
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027552" ON "ADMIN"."MBTA_ROUTEINFO" ("ROUTEID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MBTA_ROUTEINFO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" MODIFY ("ROUTEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" MODIFY ("TYPEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" MODIFY ("ROUTE_FROM" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" MODIFY ("ROUTE_TO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" MODIFY ("DURATION" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" ADD PRIMARY KEY ("ROUTEID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MBTA_ROUTEINFO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_ROUTEINFO" ADD FOREIGN KEY ("TYPEID")
	  REFERENCES "ADMIN"."MBTA_TYPES" ("TYPEID") ENABLE;
