--------------------------------------------------------
--  File created - Tuesday-December-14-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MBTA_SCHEDULE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_SCHEDULE" 
   (	"SCHEDULEID" NUMBER(*,0), 
	"TRAINID" NUMBER(*,0), 
	"ROUTEID" NUMBER(*,0), 
	"TRAINTIME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027544
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027544" ON "ADMIN"."MBTA_SCHEDULE" ("SCHEDULEID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MBTA_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_SCHEDULE" MODIFY ("SCHEDULEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_SCHEDULE" MODIFY ("TRAINID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_SCHEDULE" MODIFY ("ROUTEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_SCHEDULE" MODIFY ("TRAINTIME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_SCHEDULE" ADD PRIMARY KEY ("SCHEDULEID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MBTA_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_SCHEDULE" ADD FOREIGN KEY ("TRAINID")
	  REFERENCES "ADMIN"."MBTA_TRAININFO" ("TRAINID") ENABLE;
  ALTER TABLE "ADMIN"."MBTA_SCHEDULE" ADD FOREIGN KEY ("ROUTEID")
	  REFERENCES "ADMIN"."MBTA_ROUTEINFO" ("ROUTEID") ENABLE;
