--------------------------------------------------------
--  File created - Tuesday-December-14-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MBTA_TRAINCURRENTSTATUS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_TRAINCURRENTSTATUS" 
   (	"TRAINCURRENTSTATUSID" NUMBER(*,0), 
	"LATITUDE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"LONGITUDE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"TRAINID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027567
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027567" ON "ADMIN"."MBTA_TRAINCURRENTSTATUS" ("TRAINCURRENTSTATUSID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MBTA_TRAINCURRENTSTATUS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_TRAINCURRENTSTATUS" MODIFY ("TRAINCURRENTSTATUSID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_TRAINCURRENTSTATUS" ADD PRIMARY KEY ("TRAINCURRENTSTATUSID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MBTA_TRAINCURRENTSTATUS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_TRAINCURRENTSTATUS" ADD FOREIGN KEY ("TRAINID")
	  REFERENCES "ADMIN"."MBTA_TRAININFO" ("TRAINID") ENABLE;
