--------------------------------------------------------
--  File created - Tuesday-December-14-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MBTA_TRAININFO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MBTA_TRAININFO" 
   (	"TRAINID" NUMBER(*,0), 
	"TRAINSERIALNO" NUMBER(*,0), 
	"YEAROFMANUFACTURING" NUMBER(4,0), 
	"LASTSERVICEDATE" DATE, 
	"CAPACITY" NUMBER(*,0), 
	"EMPLOYEEID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027539
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0027539" ON "ADMIN"."MBTA_TRAININFO" ("TRAINID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MBTA_TRAININFO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_TRAININFO" MODIFY ("TRAINID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_TRAININFO" MODIFY ("TRAINSERIALNO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_TRAININFO" MODIFY ("YEAROFMANUFACTURING" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_TRAININFO" MODIFY ("CAPACITY" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_TRAININFO" MODIFY ("EMPLOYEEID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MBTA_TRAININFO" ADD PRIMARY KEY ("TRAINID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MBTA_TRAININFO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MBTA_TRAININFO" ADD FOREIGN KEY ("EMPLOYEEID")
	  REFERENCES "ADMIN"."MBTA_EMPLOYEE" ("EMPLOYEEID") ENABLE;
